apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: novo-projeto
  labels:
    app: test-app
spec:
  # Define how many identical Pods should be running
  replicas: 5
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      namespace: novo-projeto
      labels:
        app: test-app
        cluster.x-k8s.io/drain: skip
    spec:
      containers:
      - name: nginx-container
        # Use a common, small image
        image: nginx:latest
        ports:
        - containerPort: 80
