apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: test-pdb
  namespace: cattle-system
spec:
  minAvailable: 3
  minUnavailable: 2
  selector:
    matchLabels:
      app: cattle-cluster-agent
